[custom.all.irpn]
type = "local"
path = "."
ipkg = "irpn.ipkg"
test = "test/test.ipkg"

[custom.all.irpn-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.hashmap]
type   = "github"
url    = "https://github.com/Z-snails/idris2-hashmap"
commit = "latest:main"
ipkg   = "hashmap.ipkg"