name: Docker Image CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ghcr.io/stefan-hoeck/idris2-pack:latest
    types: [completed]
    branches: ["main"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build using Docker
      run: make irpn
    - name: Debug
      run: ls -al
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pages-site
        path: |
          index.html
          build/exec/irpn.js
