name: CI

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: pack install-deps irpn.ipkg
    - name: Compile Idris Source to JS
      run: pack build irpn.ipkg
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pages-site
        path: |
          index.html
          build/exec/irpn.js
