name: Deploy to pages

on:
  workflow_dispatch

# XXX: added this comment to allow me to save what was already here.

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between
# the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        id: deployment
        uses: actions/download-build-artifact@v3
        with:
          name: pages-site
      - name: Unpack archive
        run: ls -al
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          
