name: Old CI

on:
  workflow_dispatch:

# XXX: added this comment to allow me to save what was already here.

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between
# the run in-progress and latest queued.
concurrency:
  group: "pages"


jobs:
  build:
    runs-on: ghcr.io/stefan-hoeck/idris2-pack:latest
    types: [completed]
    branches: ["main"]

    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag irpn
    - name: Create docker container from image
      run: docker create irpn > img_id
    - name: Copy build artifact out of the container
      run: docker cp "$(cat img_id):build/" .
    - name: OMG WTF
      run: ls -al
=======
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile Idris Source to JS
      run: pack build irpn.ipkg
>>>>>>> d13cf08 (Create a CI workflow which runs directly on the stephan's container)
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pages-site
        path: |
          index.html
          build/exec/irpn.js
